package:
    type:           yii2-extension
    name:           hipanel-module-server
    title:          Server module for HiPanel
    headline:       HiPanel Server Module
    keywords:       server, hipanel, plugin
    namespace:      hipanel\modules\server
    description:    |
        [![Logo](https://raw.githubusercontent.com/hiqdev/hipanel-core/master/docs/logo.png)](https://hipanel.com/)

        [HiPanel](http://hipanel.com) is the next generation control panel for hosting, domains and more.

        This package provides server management for HiPanel.

require:
    hiqdev/hidev-php:       "*"
    hiqdev/hidev-vendor:    "*"
